---
name: Run tests
"on": [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install dependencies
        run: python3 -m pip install -r pip-tools/dev-requirements.txt
      - name: Test
        run: python3 -m pytest tests/unit
